Added insert/select collection backend
tomjacobson612/Trade-Binder pull request #11
Opened 2023-11-07 21:23 UTC by tnoyespdx

Implemented two fields in the collection table "name" and "num". Created functions for inserting into the database and for reading all items in the database. Also created some stub files for the add.html and collection.html pages which will be used for the inserting and reading of the collection.

2023-11-07 21:29 UTC, tomjacobson612 commented
Looks good. We may want to tweak the collection table to also be able to store things like image url so we can display that to the user but this will be sufficient for now.

2023-11-07 21:32 UTC, tomjacobson612 requested changes
Can you add a field to the table for image url so that we can display collection graphically. Should add exception handling for failed connections, failed inserts, etc.

2023-11-08 03:11 UTC, tnoyespdx commented
Okay should be added now with a little error handling and an image field for the database

2023-11-08 20:35 UTC, tomjacobson612 approved these changes

2023-11-08 20:38 UTC, merged